#include "module.h"
#include "core.h"
#include "peripheral.h"
#include "dataset.h"
#include "malloc.h"

DDS MW_1(XPAR_DDS_CONTROLLER_00_BASEADDR); // dds_00

DDS IND1_1(XPAR_DDS_CONTROLLER_01_BASEADDR); // dds_01

DDS IND2_1(XPAR_DDS_CONTROLLER_02_BASEADDR); // dds_02

DDS IND3_1(XPAR_DDS_CONTROLLER_03_BASEADDR); // dds_03

DDS IND4_1(XPAR_DDS_CONTROLLER_04_BASEADDR); // dds_04

DDS dds_05(XPAR_DDS_CONTROLLER_05_BASEADDR);

DDS IND5_1(XPAR_DDS_CONTROLLER_06_BASEADDR); // dds_06

DDS dds_07(XPAR_DDS_CONTROLLER_07_BASEADDR);

DDS MW_2(XPAR_DDS_CONTROLLER_10_BASEADDR); // dds_10

DDS IND1_2(XPAR_DDS_CONTROLLER_11_BASEADDR); // dds_11

DDS IND2_2(XPAR_DDS_CONTROLLER_12_BASEADDR); // dds_12

DDS IND3_2(XPAR_DDS_CONTROLLER_13_BASEADDR); // dds_13

DDS IND4_2(XPAR_DDS_CONTROLLER_14_BASEADDR); // dds_14

DDS dds_15(XPAR_DDS_CONTROLLER_15_BASEADDR);

DDS IND5_2(XPAR_DDS_CONTROLLER_16_BASEADDR); // dds_16

DDS dds_17(XPAR_DDS_CONTROLLER_17_BASEADDR);

RamanPID_Controller raman_pid_controller(XPAR_PHASE_ESTIMATOR_0_BASEADDR);

InputController input_controller_0(XPAR_INPUTCONTROLLER_8_BASEADDR);
InputController input_controller_1(XPAR_INPUTCONTROLLER_9_BASEADDR);
InputController ION1_PMT3(XPAR_INPUTCONTROLLER_0_BASEADDR); // ja_1
InputController ION2_PMT4(XPAR_INPUTCONTROLLER_1_BASEADDR); // ja_2
InputController ION3_PMT5(XPAR_INPUTCONTROLLER_2_BASEADDR); // ja_3
InputController ION4_PMT6(XPAR_INPUTCONTROLLER_3_BASEADDR); // ja_4
InputController ION5_PMT7(XPAR_INPUTCONTROLLER_4_BASEADDR); // ja_5
InputController ja_6(XPAR_INPUTCONTROLLER_5_BASEADDR);
InputController ja_7(XPAR_INPUTCONTROLLER_6_BASEADDR);
InputController ja_8(XPAR_INPUTCONTROLLER_7_BASEADDR);

SwitchController MW_sw(XPAR_SWITCHCONTROLLER_0_BASEADDR); // dds_sw_0

SwitchController IND1_sw(XPAR_SWITCHCONTROLLER_1_BASEADDR); // dds_sw_1

SwitchController IND2_sw(XPAR_SWITCHCONTROLLER_2_BASEADDR); // dds_sw_2

SwitchController IND3_sw(XPAR_SWITCHCONTROLLER_3_BASEADDR); // dds_sw_3

SwitchController IND4_sw(XPAR_SWITCHCONTROLLER_4_BASEADDR); // dds_sw_4

SwitchController dds_sw_5(XPAR_SWITCHCONTROLLER_5_BASEADDR);

SwitchController IND5_sw(XPAR_SWITCHCONTROLLER_6_BASEADDR); // dds_sw_6

SwitchController dds_sw_7(XPAR_SWITCHCONTROLLER_7_BASEADDR);

// SwitchController dds_sw_0(XPAR_SWITCHCONTROLLER_0_BASEADDR); // dds_sw_0
// SwitchController dds_sw_1(XPAR_SWITCHCONTROLLER_1_BASEADDR); // dds_sw_1
// SwitchController dds_sw_2(XPAR_SWITCHCONTROLLER_2_BASEADDR); // dds_sw_2
// SwitchController dds_sw_3(XPAR_SWITCHCONTROLLER_3_BASEADDR); // dds_sw_3
// SwitchController dds_sw_4(XPAR_SWITCHCONTROLLER_4_BASEADDR); // dds_sw_4
// SwitchController dds_sw_5(XPAR_SWITCHCONTROLLER_5_BASEADDR);
// SwitchController dds_sw_6(XPAR_SWITCHCONTROLLER_6_BASEADDR); // dds_sw_6
// SwitchController dds_sw_7(XPAR_SWITCHCONTROLLER_7_BASEADDR);

/* Laser, cooling */
uint64_t * ttl_set_0_ptr = (uint64_t *) malloc(sizeof(uint64_t));
TTL jb_0(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,0); // jb_1
TTL AOM_MAIN     (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,0); // jb_1
TTL EOM2_1   (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,1); // jb_2
TTL EOM14_7  (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,2); // jb_3
TTL AOM_SPAM    (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,3); // jb_4
TTL AOM_DOPDET    (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,4); // jb_5
TTL jb_6    (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,5);
TTL AOM_SIS_1    (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,6); // jb_7
TTL AOM_SIS_2    (XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,7); // jb_8

uint64_t * ttl_set_1_ptr = (uint64_t *) malloc(sizeof(uint64_t));
TTL RAMAN_GLB(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,0); // jc_1
TTL jc_2(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,1);
TTL jc_3(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,2);
TTL jc_4(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,3);
TTL jc_5(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,4);
TTL jc_6(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,5);
TTL jc_7(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,6);
TTL jc_8(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,7);

uint64_t * ttl_set_2_ptr = (uint64_t *) malloc(sizeof(uint64_t));
TTL jd_1(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,0);
TTL jd_2(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,1);
TTL jd_3(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,2);
TTL jd_4(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,3);
TTL jd_5(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,4);
TTL jd_6(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,5);
TTL jd_7(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,6);
TTL jd_8(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,7);

DAC dac_controller_0(XPAR_SPI_CONTROLLER_0_BASEADDR);
DAC dac_controller_1(XPAR_SPI_CONTROLLER_1_BASEADDR);

TimeController tc_0(XPAR_TIMECONTROLLER_0_BASEADDR);

WaveCacheController wave_cache_controller(XPAR_WAVECACHECONTROLLER_0_BASEADDR);
WaveCacheController awg(XPAR_WAVECACHECONTROLLER_0_BASEADDR);

FLAREController flare_controller(XPAR_FLARE_AURORA_CONTROLLER_0_BASEADDR);