#include "module.h"
#include "core.h"
#include "malloc.h"

DDS dds_00(XPAR_DDS_CONTROLLER_00_BASEADDR); // dds_00

DDS dds_01(XPAR_DDS_CONTROLLER_01_BASEADDR); // dds_01

DDS IND2_1(XPAR_DDS_CONTROLLER_02_BASEADDR); // dds_02

DDS IND3_1(XPAR_DDS_CONTROLLER_03_BASEADDR); // dds_03

DDS dds_04(XPAR_DDS_CONTROLLER_04_BASEADDR);

DDS dds_05(XPAR_DDS_CONTROLLER_05_BASEADDR);

DDS IND4_1(XPAR_DDS_CONTROLLER_06_BASEADDR); // dds_06

DDS dds_07(XPAR_DDS_CONTROLLER_07_BASEADDR); // dds_07

DDS MW_2(XPAR_DDS_CONTROLLER_10_BASEADDR); // dds_10

DDS IND1_2(XPAR_DDS_CONTROLLER_11_BASEADDR); // dds_11

DDS IND2_2(XPAR_DDS_CONTROLLER_12_BASEADDR); // dds_12

DDS IND3_2(XPAR_DDS_CONTROLLER_13_BASEADDR); // dds_13

DDS dds_14(XPAR_DDS_CONTROLLER_14_BASEADDR);

DDS dds_15(XPAR_DDS_CONTROLLER_15_BASEADDR);

DDS IND4_2(XPAR_DDS_CONTROLLER_16_BASEADDR); // dds_16

DDS IND5_2(XPAR_DDS_CONTROLLER_17_BASEADDR); // dds_17

SwitchController dds_sw_0(XPAR_SWITCHCONTROLLER_0_BASEADDR);

SwitchController dds_sw_1(XPAR_SWITCHCONTROLLER_1_BASEADDR);

SwitchController dds_sw_2(XPAR_SWITCHCONTROLLER_2_BASEADDR);

SwitchController dds_sw_3(XPAR_SWITCHCONTROLLER_3_BASEADDR);

SwitchController dds_sw_4(XPAR_SWITCHCONTROLLER_4_BASEADDR);

SwitchController dds_sw_5(XPAR_SWITCHCONTROLLER_5_BASEADDR);

SwitchController dds_sw_6(XPAR_SWITCHCONTROLLER_6_BASEADDR);

SwitchController dds_sw_7(XPAR_SWITCHCONTROLLER_7_BASEADDR);

uint64_t * ttl_set_0_ptr = (uint64_t *) malloc(sizeof(uint64_t));
TTL jb_0(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,0);
TTL jb_1(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,1);
TTL jb_2(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,2);
TTL jb_3(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,3);
TTL jb_4(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,4);
TTL jb_5(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,5);
TTL jb_6(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,6);
TTL jb_7(XPAR_TTL_CONTROLLER_0_BASEADDR,ttl_set_0_ptr,7);

uint64_t * ttl_set_1_ptr = (uint64_t *) malloc(sizeof(uint64_t));
TTL jc_0(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,0);
TTL jc_1(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,1);
TTL jc_2(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,2);
TTL jc_3(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,3);
TTL jc_4(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,4);
TTL jc_5(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,5);
TTL jc_6(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,6);
TTL jc_7(XPAR_TTL_CONTROLLER_1_BASEADDR,ttl_set_1_ptr,7);

uint64_t * ttl_set_2_ptr = (uint64_t *) malloc(sizeof(uint64_t));
TTL jd_0(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,0);
TTL jd_1(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,1);
TTL jd_2(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,2);
TTL jd_3(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,3);
TTL jd_4(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,4);
TTL jd_5(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,5);
// TTL jd_6(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,6);
// TTL jd_7(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,7);
LDAC jd_6(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,6);
LDAC jd_7(XPAR_TTL_CONTROLLER_2_BASEADDR,ttl_set_2_ptr,7);

WaveCacheController wave_cache_controller(XPAR_WAVECACHECONTROLLER_0_BASEADDR);

DAC dac_controller_0(XPAR_SPI_CONTROLLER_0_BASEADDR);
DAC dac_controller_1(XPAR_SPI_CONTROLLER_1_BASEADDR);