/******************************************************************************
 * rfdc_set_nco_freq.cpp
 *
 * Bare-metal RFdc NCO frequency update utility for Vitis 2020.2.
 *
 * Assumptions:
 *   1. Bitstream / RFDC IP is already configured.
 *   2. RF clocks are stable.
 *   3. RFDC tile startup / calibration has already completed, or your main
 *      firmware has already initialized RFDC.
 *   4. The target converter's fine mixer/NCO path is enabled in the RFDC IP
 *      configuration. If the mixer is bypassed or disabled, changing NCO
 *      frequency has no visible effect.
 *
 * Default target:
 *   DAC Tile 0, Block 0, NCO frequency = 100.0 MHz
 *
 * To change target:
 *   Edit TARGET_TYPE / TARGET_TILE_ID / TARGET_BLOCK_ID / TARGET_NCO_FREQ_MHZ.
 ******************************************************************************/

extern "C" {
#include "xparameters.h"
#include "xil_printf.h"
#include "xstatus.h"

#include "xrfdc.h"

/*
 * In Vitis 2020.2, RFdc bare-metal driver uses libmetal.
 * xrfdc.h usually pulls these in, but including them explicitly makes the
 * dependency clear for a standalone .cpp application.
 */
#include "metal/sys.h"
#include "metal/device.h"
}

#include <string.h>

/* -------------------------------------------------------------------------- */
/* RFDC instance selection                                                     */
/* -------------------------------------------------------------------------- */

#ifndef XPAR_XRFDC_0_DEVICE_ID
#error "XPAR_XRFDC_0_DEVICE_ID is not defined. Check xparameters.h from your XSA/BSP."
#endif

#ifndef XPAR_XRFDC_0_BASEADDR
#error "XPAR_XRFDC_0_BASEADDR is not defined. Check xparameters.h from your XSA/BSP."
#endif

#ifndef XPAR_XRFDC_0_DEV_NAME
#error "XPAR_XRFDC_0_DEV_NAME is not defined. Use the RFdc xparameters.h generated by Vitis 2020.2, or define RFDC_DEV_NAME manually."
#endif

#define RFDC_DEVICE_ID      XPAR_XRFDC_0_DEVICE_ID
#define RFDC_BASE_ADDR      XPAR_XRFDC_0_BASEADDR
#define RFDC_DEV_NAME       XPAR_XRFDC_0_DEV_NAME

/*
 * Target converter.
 *
 * For DAC DUC NCO:
 *   TARGET_TYPE = XRFDC_DAC_TILE
 *
 * For ADC DDC NCO:
 *   TARGET_TYPE = XRFDC_ADC_TILE
 */
#define TARGET_TYPE         XRFDC_DAC_TILE
#define TARGET_TILE_ID      0U
#define TARGET_BLOCK_ID     0U

/*
 * NCO frequency in MHz.
 *
 * RFdc API uses MHz here, not Hz.
 * Example:
 *   100.0    -> 100 MHz
 *   -50.0    -> -50 MHz
 *   1.234    -> 1.234 MHz
 */
#define TARGET_NCO_FREQ_MHZ 100.0

/*
 * Usually keep phase unchanged when only changing frequency.
 * Set UPDATE_PHASE_OFFSET to 1 if you also want to overwrite PhaseOffset.
 */
#define UPDATE_PHASE_OFFSET        0
#define TARGET_NCO_PHASE_DEG       0.0

/*
 * Recommended for deterministic application inside a tile:
 *   USE_TILE_EVENT = 1:
 *      Set EventSource = XRFDC_EVNT_SRC_TILE, then call XRFdc_UpdateEvent().
 *
 * Simpler immediate update:
 *   USE_TILE_EVENT = 0:
 *      Set EventSource = XRFDC_EVNT_SRC_IMMEDIATE.
 *
 * Tile event is safer when you later update multiple blocks in the same tile.
 */
#define USE_TILE_EVENT             1

/*
 * Set to 1 only if you deliberately want to force mixer type to fine mixer.
 * In most cases, preserve existing mixer mode/type from the RFDC IP config.
 */
#define FORCE_FINE_MIXER_SETTINGS  0

/*
 * Optional NCO phase accumulator reset. Keep 0 for frequency-only update.
 */
#define RESET_NCO_PHASE_AFTER_FREQ_UPDATE 0

/* -------------------------------------------------------------------------- */
/* Global driver / libmetal objects                                            */
/* -------------------------------------------------------------------------- */

static XRFdc RFdcInst;

static struct metal_device *RfdcMetalDevicePtr = NULL;
static metal_phys_addr_t RfdcMetalPhys = RFDC_BASE_ADDR;
static struct metal_device RfdcCustomMetalDevice;

/* -------------------------------------------------------------------------- */
/* Utility print for double MHz without using %f in xil_printf                 */
/* -------------------------------------------------------------------------- */

static void PrintMHz(const char *Label, double ValueMHz)
{
    int IsNeg = 0;
    double AbsVal = ValueMHz;

    if (AbsVal < 0.0) {
        IsNeg = 1;
        AbsVal = -AbsVal;
    }

    unsigned int Whole = (unsigned int)AbsVal;
    unsigned int Milli = (unsigned int)((AbsVal - (double)Whole) * 1000.0 + 0.5);

    if (Milli >= 1000U) {
        Whole += 1U;
        Milli -= 1000U;
    }

    xil_printf("%s", Label);
    if (IsNeg) {
        xil_printf("-");
    }

    xil_printf("%d.", Whole);

    if (Milli < 100U) {
        xil_printf("0");
    }
    if (Milli < 10U) {
        xil_printf("0");
    }

    xil_printf("%d MHz\r\n", Milli);
}

/* -------------------------------------------------------------------------- */
/* C++-safe libmetal device setup                                              */
/* -------------------------------------------------------------------------- */

static void SetupRfdcMetalDevice(void)
{
    /*
     * Xilinx's C examples use C99 designated initializers for this structure.
     * In a .cpp file under Vitis 2020.2, use runtime assignment instead.
     */
    memset(&RfdcCustomMetalDevice, 0, sizeof(RfdcCustomMetalDevice));

    RfdcCustomMetalDevice.name = (char *)RFDC_DEV_NAME;
    RfdcCustomMetalDevice.bus = NULL;
    RfdcCustomMetalDevice.num_regions = 1U;

    RfdcCustomMetalDevice.regions[0].virt = (void *)RFDC_BASE_ADDR;
    RfdcCustomMetalDevice.regions[0].physmap = &RfdcMetalPhys;
    RfdcCustomMetalDevice.regions[0].size = 0x40000U;
    RfdcCustomMetalDevice.regions[0].page_shift = (unsigned int)(-1);
    RfdcCustomMetalDevice.regions[0].page_mask = (unsigned int)(-1);
    RfdcCustomMetalDevice.regions[0].mem_flags = 0x0U;

    RfdcCustomMetalDevice.irq_num = 0;
    RfdcCustomMetalDevice.irq_info = NULL;

    RfdcMetalDevicePtr = &RfdcCustomMetalDevice;
}

/* -------------------------------------------------------------------------- */
/* RFdc driver initialization                                                  */
/* -------------------------------------------------------------------------- */

static int InitRFdc(void)
{
    int Status;
    XRFdc_Config *ConfigPtr;

    struct metal_init_params InitParam = METAL_INIT_DEFAULTS;

    Status = metal_init(&InitParam);
    if (Status != 0) {
        xil_printf("ERROR: metal_init() failed, status = %d\r\n", Status);
        return XRFDC_FAILURE;
    }

    ConfigPtr = XRFdc_LookupConfig(RFDC_DEVICE_ID);
    if (ConfigPtr == NULL) {
        xil_printf("ERROR: XRFdc_LookupConfig() failed. Device ID = %d\r\n",
                   RFDC_DEVICE_ID);
        return XRFDC_FAILURE;
    }

    SetupRfdcMetalDevice();

    Status = XRFdc_RegisterMetal(&RFdcInst, RFDC_DEVICE_ID, &RfdcMetalDevicePtr);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: XRFdc_RegisterMetal() failed, status = %d\r\n",
                   Status);
        return XRFDC_FAILURE;
    }

    Status = XRFdc_CfgInitialize(&RFdcInst, ConfigPtr);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: XRFdc_CfgInitialize() failed, status = %d\r\n",
                   Status);
        return XRFDC_FAILURE;
    }

    xil_printf("RFdc driver initialized.\r\n");
    return XRFDC_SUCCESS;
}

/* -------------------------------------------------------------------------- */
/* Optional sanity check                                                       */
/* -------------------------------------------------------------------------- */

static int CheckTargetBlockEnabled(u32 Type, u32 Tile, u32 Block)
{
    u32 Enabled = 0U;

    if (Type == XRFDC_DAC_TILE) {
        Enabled = XRFdc_IsDACBlockEnabled(&RFdcInst, Tile, Block);
        if (Enabled == 0U) {
            xil_printf("ERROR: DAC Tile %d Block %d is not enabled.\r\n",
                       Tile, Block);
            return XRFDC_FAILURE;
        }
    } else if (Type == XRFDC_ADC_TILE) {
        Enabled = XRFdc_IsADCBlockEnabled(&RFdcInst, Tile, Block);
        if (Enabled == 0U) {
            xil_printf("ERROR: ADC Tile %d Block %d is not enabled.\r\n",
                       Tile, Block);
            return XRFDC_FAILURE;
        }
    } else {
        xil_printf("ERROR: Invalid TARGET_TYPE = %d\r\n", Type);
        return XRFDC_FAILURE;
    }

    return XRFDC_SUCCESS;
}

/* -------------------------------------------------------------------------- */
/* NCO frequency update                                                        */
/* -------------------------------------------------------------------------- */

static int SetNcoFrequencyMHz(u32 Type, u32 Tile, u32 Block, double FreqMHz)
{
    int Status;
    XRFdc_Mixer_Settings MixerSettings;
    XRFdc_Mixer_Settings ReadbackSettings;

    memset(&MixerSettings, 0, sizeof(MixerSettings));
    memset(&ReadbackSettings, 0, sizeof(ReadbackSettings));

    /*
     * Read current mixer settings first.
     * This preserves MixerMode, MixerType, CoarseMixFreq, FineMixerScale, etc.
     */
    Status = XRFdc_GetMixerSettings(&RFdcInst, Type, Tile, Block,
                                    &MixerSettings);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: XRFdc_GetMixerSettings() failed, status = %d\r\n",
                   Status);
        return XRFDC_FAILURE;
    }

    /*
     * Change only the NCO frequency.
     * Unit: MHz.
     */
    MixerSettings.Freq = FreqMHz;

#if UPDATE_PHASE_OFFSET
    MixerSettings.PhaseOffset = TARGET_NCO_PHASE_DEG;
#endif

#if FORCE_FINE_MIXER_SETTINGS
    /*
     * Use this only when you know the datapath is configured for the fine mixer.
     * If the IP was generated with the mixer disabled/bypassed, forcing this
     * will not magically instantiate the mixer.
     */
    MixerSettings.CoarseMixFreq = XRFDC_COARSE_MIX_OFF;
    MixerSettings.MixerType = XRFDC_MIXER_TYPE_FINE;
    MixerSettings.FineMixerScale = XRFDC_MIXER_SCALE_AUTO;
#endif

#if USE_TILE_EVENT
    MixerSettings.EventSource = XRFDC_EVNT_SRC_TILE;
#else
    MixerSettings.EventSource = XRFDC_EVNT_SRC_IMMEDIATE;
#endif

    Status = XRFdc_SetMixerSettings(&RFdcInst, Type, Tile, Block,
                                    &MixerSettings);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: XRFdc_SetMixerSettings() failed, status = %d\r\n",
                   Status);
        return XRFDC_FAILURE;
    }

#if RESET_NCO_PHASE_AFTER_FREQ_UPDATE
    /*
     * Optional: arm/reset NCO phase accumulator according to the selected
     * event source. For frequency-only update, leave disabled.
     */
    Status = XRFdc_ResetNCOPhase(&RFdcInst, Type, Tile, Block);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: XRFdc_ResetNCOPhase() failed, status = %d\r\n",
                   Status);
        return XRFDC_FAILURE;
    }
#endif

#if USE_TILE_EVENT
    /*
     * Apply the mixer/NCO update.
     * For TILE event, one block's update event triggers the tile mixer update.
     */
    Status = XRFdc_UpdateEvent(&RFdcInst, Type, Tile, Block, XRFDC_EVENT_MIXER);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: XRFdc_UpdateEvent() failed, status = %d\r\n",
                   Status);
        return XRFDC_FAILURE;
    }
#endif

    Status = XRFdc_GetMixerSettings(&RFdcInst, Type, Tile, Block,
                                    &ReadbackSettings);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: readback XRFdc_GetMixerSettings() failed, status = %d\r\n",
                   Status);
        return XRFDC_FAILURE;
    }

    xil_printf("NCO update completed.\r\n");
    PrintMHz("Requested NCO frequency: ", FreqMHz);
    PrintMHz("Readback  NCO frequency: ", ReadbackSettings.Freq);

    return XRFDC_SUCCESS;
}

/* -------------------------------------------------------------------------- */
/* Main                                                                        */
/* -------------------------------------------------------------------------- */

int main(void)
{
    int Status;

    xil_printf("\r\n");
    xil_printf("========================================\r\n");
    xil_printf(" RFdc NCO Frequency Update Utility\r\n");
    xil_printf(" Vitis 2020.2 Bare-metal C++\r\n");
    xil_printf("========================================\r\n");

    xil_printf("Target type : %s\r\n",
               (TARGET_TYPE == XRFDC_DAC_TILE) ? "DAC" : "ADC");
    xil_printf("Target tile : %d\r\n", TARGET_TILE_ID);
    xil_printf("Target block: %d\r\n", TARGET_BLOCK_ID);
    PrintMHz("Target freq : ", TARGET_NCO_FREQ_MHZ);

    Status = InitRFdc();
    if (Status != XRFDC_SUCCESS) {
        xil_printf("FAILED: RFdc initialization failed.\r\n");
        return XRFDC_FAILURE;
    }

    Status = CheckTargetBlockEnabled(TARGET_TYPE, TARGET_TILE_ID, TARGET_BLOCK_ID);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("FAILED: target block check failed.\r\n");
        return XRFDC_FAILURE;
    }

    Status = SetNcoFrequencyMHz(TARGET_TYPE,
                                TARGET_TILE_ID,
                                TARGET_BLOCK_ID,
                                TARGET_NCO_FREQ_MHZ);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("FAILED: NCO frequency update failed.\r\n");
        return XRFDC_FAILURE;
    }

    xil_printf("SUCCESS: RFdc NCO frequency updated.\r\n");

    /*
     * Returning is fine for a JTAG-run utility.
     * If your boot/runtime environment expects the CPU not to exit, replace
     * the return with:
     *
     *   while (1) { }
     */
    return XRFDC_SUCCESS;
}